# Generated by Django 4.0.5 on 2022-11-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('eid', models.IntegerField()),
                ('esalary', models.IntegerField()),
                ('egender', models.CharField(max_length=1)),
                ('estatus', models.CharField(max_length=30)),
                ('edept', models.CharField(max_length=30)),
                ('egrade', models.IntegerField()),
                ('e_personalId', models.CharField(max_length=30)),
                ('e_post', models.CharField(max_length=30)),
            ],
        ),
    ]
